[package]
name = "rattler_solve"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to solve conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rattler_conda_types = { workspace = true }
rattler_digest = { workspace = true }
libc = { workspace = true, optional = true }
anyhow = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }
rattler_libsolv_c = { workspace = true, optional = true }
resolvo = { workspace = true, optional = true }

[dev-dependencies]
rattler_repodata_gateway = { version = "0.16.2", path = "../rattler_repodata_gateway", default-features = false, features = ["sparse"] }
insta = { version = "1.33.0", features = ["yaml"] }
rstest = "0.18.2"
serde_json = "1.0.107"
url = "2.4.1"
similar-asserts = "1.5.0"
once_cell = "1.18.0"
criterion = "0.5.1"
test-log = { version = "0.2.12", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[features]
default = ["libsolv_c"]
libsolv_c = ["rattler_libsolv_c", "libc"]

[[bench]]
name = "bench"
harness = false
