[package]
name = "rattler"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust library to install conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls', 'rattler_package_streaming/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_package_streaming/rustls-tls']

[dependencies]
anyhow = { workspace = true }
async-compression = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
digest = { workspace = true }
dirs = { workspace = true }
drop_bomb = { workspace = true }
futures = { workspace = true }
fxhash = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
memchr = { workspace = true }
memmap2 = { workspace = true }
nom = { workspace = true }
once_cell = { workspace = true }
pin-project-lite = { workspace = true }
rattler_conda_types = { workspace = true }
rattler_digest = { workspace = true }
rattler_networking = { workspace = true }
rattler_package_streaming = { workspace = true, features = ["reqwest"] }
reflink-copy = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["stream", "json", "gzip"] }
reqwest-middleware = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
smallvec = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "io-util", "macros"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["codec", "io"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "fast-rng"] }

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.5"
rstest = "0.18.2"
tracing-test = { version = "0.2.4" }
insta = { version = "1.33.0", features = ["yaml"] }
rattler_lock = { path = "../rattler_lock" }

tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
axum = "0.6.20"
tower-http = { version = "0.4.4", features = ["fs"] }
tower = { version = "0.4.13", default-features = false, features = ["util"] }
